# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            6

# Build settings
markdown:            kramdown
theme:               null
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: false
  tables: false

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Ning'
description:	       'Personal Blog'
author:              'the Jekyll theme Lagrange'

# Comments
comments:
  provider: valine
  valine:
    app_id: StwOUiVAVTVdsND5kOqvM7dy-gzGzoHsz # your app_id
    app_key: TqViHH2IJYdOvjUm5H6eZJcn # your app_key
    placeholder: Add your comments here...
    avatar: mp
    meta: [nick, mail, link]
    pageSize: 10
    lang: en
    visitor: false
    highlight: true
    recordIP: false

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

collections:
  gallery:
    output: true

include:
  - "_posts/post_image"
